name: Yarn Install
description: Install Yarn Dependencies

runs:
  using: composite
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: yarn
    - name: Install
      shell: bash
      run: yarn install --immutable
