version: '3.8'

services:
  frontend:
    environment:
      HOST: ${HOST}
      CLIENT_PORT: 80
    image: lafontaine/frontend
    ports:
      - 80:80
    build:
      context: frontend
      dockerfile: Dockerfile
  backend:
    environment:
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}  
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: 80
      DIALECT: ${DIALECT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: lafontainemons
    image: lafontaine/backend
    ports:
      - ${SERVER_PORT}:8080
    build:
      context: backend
      dockerfile: Dockerfile
  postgres:
    image: postgres:14-alpine
    hostname: lafontaine-postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: lafontainemons
