version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    links:
      - backend
    environment:
      HOST: ${HOST}
      CLIENT_PORT: ${CLIENT_PORT}
    image: lafontaine/frontend
    ports:
      - ${CLIENT_PORT}:8081
    build:
      context: frontend
      dockerfile: Dockerfile
  backend:
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
      DIALECT: ${DIALECT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: lafontainemons
    image: lafontaine/backend
    ports:
      - ${SERVER_PORT}:8080
    build:
      context: backend
      dockerfile: Dockerfile
  postgres:
    image: postgres:14-alpine
    hostname: lafontaine-postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: lafontainemons
