version: '3.8'

services:
  frontend:
    environment:
      HOST: ${HOST}
      CLIENT_PORT: ${CLIENT_PORT}
    image: lafontaine/frontend
    ports:
      - ${CLIENT_PORT}:8081
    build:
      context: frontend
      dockerfile: Dockerfile

  backend:
    environment:
      HOST: ${HOST}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
      USER: ${USER}
      DB: ${DB}
      DIALECT: ${DIALECT}
    image: lafontaine/backend
    build:
      context: backend
      dockerfile: Dockerfile

  postgres:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lafontainemons
