services:
  frontend:
    depends_on:
      - backend
    links:
      - backend
    environment:
      HOST: ${HOST}
      CLIENT_PORT: 80
    image: lafontaine/frontend
    ports:
      - 80:80
    build:
      context: frontend
      dockerfile: Dockerfile
  backend:
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: 80
      DIALECT: ${DIALECT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    image: lafontaine/backend
    ports:
      - ${SERVER_PORT}:8080
    build:
      context: backend
      dockerfile: Dockerfile
  postgres:
    image: postgres:latest
    hostname: lafontaine-postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
