services:
  postgres:
    image: postgres:17
    container_name: lafontaine-postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lafontaine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  drizzle-migration:
    image: node:22-alpine
    container_name: lafontaine-drizzle-migration
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=https://carte.lafontainemons.be
      - BACKEND_PORT=3001
    command: sh -c "cd backend/drizzle && npm install && npx drizzle-kit push"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lafontaine-network

  seeder:
    image: postgres:17
    container_name: lafontaine-seeder
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/seeds:/seeds
    command: sh -c "sleep 10 && PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /seeds/insert_data.sql"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lafontaine-network

networks:
  lafontaine-network:
    driver: bridge

volumes:
  postgres_data: