services:
  postgres:
    image: postgres:17
    container_name: lafontaine-postgres-dev
    restart: always
    env_file:
      - ./environments/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lafontaine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  drizzle-migration:
    image: node:22-alpine
    container_name: lafontaine-drizzle-migration
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - ./environments/.env.dev
    command: sh -c "cd backend/drizzle && npm install && npx drizzle-kit push:pg"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lafontaine-network

  seeder:
    image: postgres:17
    container_name: lafontaine-seeder
    env_file:
      - ./environments/.env.dev
    volumes:
      - ./db/seeds:/seeds
    entrypoint: /bin/bash
    command:
      - -c
      - |
        sleep 10
        PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /seeds/insert_data.sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lafontaine-network

networks:
  lafontaine-network:
    driver: bridge

volumes:
  postgres_data: