-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.item
(
    "itemId" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    section character varying NOT NULL,
    subsection character varying,
    name character varying NOT NULL,
    capacity integer,
    price integer NOT NULL,
    picture character varying,
    PRIMARY KEY ("itemId")
);
END;