
name: Biome

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  biome:
    runs-on: ubuntu-latest
    name: Biome Lint & Format Check
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run Biome Check
        run: npm run lint