name: Biome

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  biome:
    runs-on: ubuntu-latest
    name: Biome
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Biome CI
        run: npx biome ci .