name: CI Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Code & Dependencies
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate environment file
        run: npm run generate-env --workspace=frontend
        env:
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          FACEBOOK_URL: ${{ secrets.FACEBOOK_URL }}
          TRIPADVISOR_URL: ${{ secrets.TRIPADVISOR_URL }}
          GOOGLE_URL: ${{ secrets.GOOGLE_URL }}
          NODE_ENV: "development"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: TypeScript check - All workspaces
        run: npm run typecheck:all

      - name: Build database (required by backend)
        run: npm run build --workspace=database

      - name: Build backend
        run: npm run build --workspace=backend

      - name: Build frontend
        run: npm run build --workspace=frontend

      # Security checks for Dependabot PRs
      - name: Security audit
        if: github.actor == 'dependabot[bot]'
        run: |
          echo "## Security Audit Report" >> $GITHUB_STEP_SUMMARY
          npm audit --audit-level=moderate || true
          
      - name: License check
        if: github.actor == 'dependabot[bot]'
        run: |
          npx license-checker --summary --excludePrivatePackages > license-summary.txt || true
          if [ -s license-summary.txt ]; then
            echo "## License Summary" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat license-summary.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi
        continue-on-error: true