name: Validate Dependencies

on:
  pull_request:
    paths:
      - 'package*.json'
      - '**/package*.json'
      - '.github/workflows/dependabot-validation.yml'

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [root, database, backend, frontend]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install all dependencies
        run: npm ci --workspaces --include-workspace-root

      - name: Build database first (required by backend)
        if: matrix.workspace == 'backend'
        run: npm run build --workspace=database

      - name: Run type checking (root)
        if: matrix.workspace == 'root'
        run: npm run typecheck:all || true
        continue-on-error: true

      - name: Run type checking (workspace)
        if: matrix.workspace != 'root'
        run: npm run typecheck --workspace=${{ matrix.workspace }}
        continue-on-error: true

      - name: Run linting
        if: matrix.workspace == 'root'
        run: npm run lint

      - name: Check for vulnerabilities
        run: npm audit --audit-level=moderate --workspace=${{ matrix.workspace }} || true
        if: matrix.workspace != 'root'
        continue-on-error: true

      - name: Check for vulnerabilities (root)
        if: matrix.workspace == 'root'
        run: npm audit --audit-level=moderate || true
        continue-on-error: true

      - name: Build project (backend)
        if: matrix.workspace == 'backend'
        run: npm run build --workspace=backend

      - name: Build project (frontend)
        if: matrix.workspace == 'frontend'
        run: npm run build --workspace=frontend

      - name: Build project (database)
        if: matrix.workspace == 'database'
        run: npm run build --workspace=database

      - name: Check bundle size (frontend)
        if: matrix.workspace == 'frontend'
        run: |
          echo "Checking bundle size..."
          ls -lah frontend/dist/frontend/browser/ || true
        continue-on-error: true

  security-check:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Security Audit
        run: |
          npm audit --json > audit-report.json || true
          if [ -s audit-report.json ]; then
            echo "## Security Audit Report" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat audit-report.json | jq '.vulnerabilities' >> $GITHUB_STEP_SUMMARY || true
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi

      - name: License Checker
        run: |
          npx license-checker --summary --excludePrivatePackages > license-summary.txt || true
          if [ -s license-summary.txt ]; then
            echo "## License Summary" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat license-summary.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi
        continue-on-error: true