name: PR checks

on:
  pull_request:

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/yarn-install
      - name: Typescript compiler check
        run: yarn turbo typecheck

  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .
